# -------------------------------------------------------------------------------------
# Hugo Configuration | Hugo 配置
# See: https://gohugo.io/configuration/all/
# -------------------------------------------------------------------------------------

# website title
# 网站标题
title = "FixIt"

# Hostname (and path) to the root
# 根目录的主机名（和路径）
baseURL = "http://localhost:1313/"

# theme
# 主题
# theme = ["FixIt", "shortcode-rewards"]

# determines default content language ["en", "zh-cn", "fr", "pl", ...]
# 设置默认的语言 ["en", "zh-cn", "fr", "pl", ...]
defaultContentLanguage = "en"
# disableLanguages = ["zh-cn"]
# whether to include Chinese/Japanese/Korean
# 是否包括中日韩文字
hasCJKLanguage = false
# Timezone Local
# 时区
timeZone = "Asia/Shanghai"

# copyright description used only for seo schema
# 版权描述，仅仅用于 SEO
copyright = ""

# whether to use robots.txt
# 是否使用 robots.txt
enableRobotsTXT = true
# whether to use git commit log
# 是否使用 git 信息
enableGitInfo = true
# whether to use emoji code
# 是否使用 emoji 代码
enableEmoji = true
# the main sections of a site
# 主站点的主要部分
mainSections = [
  "contributing",
  "documentation",
  "ecosystem",
  "guides",
  "references",
  "guides",
]

# the editor to use when creating new content
# 创建新内容时使用的编辑器
newContentEditor = "code"

# whether to capitalize automatic list titles
# 是否自动大写列表标题
titleCaseStyle = "ap"
capitalizeListTitles = false

# ignore some build errors
# 忽略一些构建错误
ignoreLogs = [
  "error-get-remote-json",
  "error-get-gh-repo",
  "error-remote-getjson",
  "error-missing-instagram-accesstoken",
  "err-youtube-remote",
  "warning-dev-version",
  "shortcode-x-getremote",
]
