# -------------------------------------------------------------------------------------
# Imaging Configuration | 图像配置
# See: https://gohugo.io/configuration/imaging/
# -------------------------------------------------------------------------------------

_merge = "shallow"
quality = 75
