# -------------------------------------------------------------------------------------
# Theme Core Configuration | 主题核心配置
# See: https://fixit.lruihao.cn/documentation/basics/#theme-configuration
# -------------------------------------------------------------------------------------

[gitInfo]
dir = "content/en"

[search]

[search.algolia]
index = "index.en"

[cse]

[cse.google]
cx = "27010f0a2633d4da4"

[postChat]
userDesc = "If you have any questions about FixIt, you can ask me~"
defaultChatQuestions = [
  "How to install the FixIt theme?",
  "What features does the FixIt theme have?",
  "FixIt theme ecosystem"
]
defaultSearchQuestions = [
  "Quick Start",
  "Configure FixIt",
  "Content Management",
  "Advanced Usage"
]

[postSummary]
title = "AI Summary"

[header]

[header.subtitle]
name = "Theme for Hugo"

[home]

[home.profile]
subtitle = "A Clean, Elegant but Advanced Hugo Theme"

[social]
GitHub = "hugo-fixit"
Twitter = "lruihao"
Email = "fixit@lruihao.cn"
RSS = true

[social.zsxq]
id = "CE3GF"
Weight = 70
Prefix = "https://t.zsxq.com/"
Title = "Hugo FixIt Planet"

[social.zsxq.icon]
Src = "images/icons/zsxq.svg"

[social.QQGroup]
id = "awbwdTtSQ_-H5QGzeJxdWgv6JMbNehNM"
Title = "FixIt QQ group"

[watermark]
content = '<img class="fixit-icon" src="/images/hugo-fixit.webp" alt="FixIt logo" /> FixIt Theme'
