# -------------------------------------------------------------------------------------
# Taxonomies Configuration | 分类法配置
# See: https://gohugo.io/configuration/taxonomies/
# -------------------------------------------------------------------------------------

category = "categories"
tag = "tags"
collection = "collections"
