# -------------------------------------------------------------------------------------
# Front Matter Configuration | Front Matter 配置
# See: https://gohugo.io/configuration/front-matter/
# -------------------------------------------------------------------------------------

lastmod = [
  "lastmod",
  ":fileModTime",
  ":git",
  ":defalut"
]
